apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: finance-tracker
  labels:
    app: redis
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/redis
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: finance-tracker
  labels:
    app: redis
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
