apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: finance-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          ports:
            - containerPort: 80
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SEQ_FIRSTRUN_NOAUTHENTICATION
              value: "True"
          volumeMounts:
            - name: seq-data
              mountPath: /data
      volumes:
        - name: seq-data
          emptyDir: {}
