receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

connectors:
  spanmetrics:
    metrics_flush_interval: 15s

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [spanmetrics, otlp/jaeger]
    metrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
